name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Add known hosts (e.g., your server's host key)
      - name: Add to Known Hosts
        run: |
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      # Step 4: Deploy files to IIS server using SCP
      - name: Deploy to IIS Server
        run: |
          scp -r ./your-site-files/ desktop-kf3loac\aniket@192.168.1.16:/C:\inetpub\wwwroot\testfile
