name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Debug Connectivity
      - name: Debug Connectivity
        run: |
          echo "Testing server connectivity..."
          timeout 5 ping -c 4 192.168.1.16 || echo "Ping failed"
          timeout 5 nc -zv 192.168.1.16 22 || echo "Port 22 not accessible"
          echo "All debug commands executed."

      # Step 3: Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 4: Add SSH Host Key
      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H 192.168.1.16 >> ~/.ssh/known_hosts

      # Step 5: Deploy files to IIS Server using SCP
      - name: Deploy to IIS Server
        run: |
          scp -r ./your-site-files/ desktop-kf3loac@192.168.1.16:/C/inetpub/wwwroot/TESTING

