name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Connectivity
        run: |
         echo "Testing server connectivity..."
         timeout 5 ping -c 4 192.168.1.16 || echo "Ping failed"
         timeout 5 nc -zv 192.168.1.16 22 || echo "Port 22 not accessible"
         timeout 5 ssh-keyscan -H 192.168.1.16 || echo "SSH keyscan failed"
         echo "All debug commands executed."




      # Step 2: Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Add known hosts (e.g., your server's host key)
      - name: Add SSH Host Key
        run: |
         ssh-keyscan -H 192.168.1.16 >> ~/.ssh/known_hosts


      # Step 4: Deploy files to IIS server using SCP
      - name: Deploy to IIS Server
        run: |
          scp -r ./your-site-files/ desktop-kf3loac\aniket@192.168.1.16:/C/inetpub/wwwroot/TESTING
